osx:
    type: osx
    info:
        name: ring
        version: nightly
        release: 1
    brew_deps:
        - automake
        - libtool
        - gettext
        - yasm
        - autoconf
        - pkg-config
        - qt5
        - llvm --with-clang --with-asan
    commands:
        - echo "Deamon"
        - git clone https://gerrit-ring.savoirfairelinux.com/ring-daemon ring-daemon
        - cd ring-daemon
        - cd contrib
        - mkdir native
        - cd native
        - ../bootstrap
        - echo "########################################################1"
        - make -j3
        - echo "########################################################2"
        - cd ../../
        - ./autogen.sh && ./configure --without-alsa --without-pulse --without-dbus --prefix=%(prefix_path)s
        - echo "########################################################3"
        - make install -j
        - echo "########################################################4"
        - cd ..
        - echo "LRC"
        - export CMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.4.0
        - git clone https://gerrit-ring.savoirfairelinux.com/ring-lrc.git ring-lrc
        - cd ring-lrc
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_INSTALL_PREFIX=%(prefix_path)s -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++
        - echo "########################################################5"
        - make install
        - echo "########################################################6"
        - cd ../../
        - echo "Client"
        - git clone https://gerrit-ring.savoirfairelinux.com/ring-client-macosx ring-client-macosx
        - cd ring-client-macosx
        - mkdir build && cd build
        - export CMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.4.0
        - cmake ../ -DCMAKE_INSTALL_PREFIX=%(prefix_path)s
        - echo "########################################################7"
        - make install -j
        - echo "########################################################8"
        - cpack -G DragNDrop Ring
    transfer:
        files:
            - ring-client-macosx/build/Ring.dmg
